version: '3'
services:
  spring-app:
    container_name: spring-app
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - youquiz
    depends_on:
      - psql-db
  psql-db:
    container_name: psql-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "quizz"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "nezha123"
    networks:
      - youquiz
networks:
  youquiz: